spring:
  application:
    name: olive-service-b

server:
  port: 8702 #${PORT:${SERVER_PORT:0}} 随机指定个没使用的端口

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8601/eureka/ #eureka服务注册地址
          
#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.2.6:3306/xjzx-main?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: root
  password: 123456

#mybatis config
mybatis:
  typeAliasesPackage: com.info.base.model
  mapperLocations: classpath:mapper/*.xml