
server:
  port: 8901

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8601/eureka/ #eureka服务注册地址

# git管理配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/olive-07/springcloud-config/ #git仓库地址
          searchPaths: demo* #搜索路径
#          username: username
#          password: password
  application:
    name: olive-configserver
#management:
#  security:
#    enabled: false

#encrypt.key 对应 git webhooks的secret
#encrypt:
#  key: olive


